/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecsite;

import static ecsite.AdminLogInForm.getOracleConnection;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author razu
 */
public class ProductUpdateForm extends javax.swing.JFrame {

    JDialog jDialog;
    
    static int INSERT_NEW_PRODUCT=5;
    static int UPDATE_PRODUCT=6;
    
    public int TASK;
    public String ProductImageLink=""; 
    public String SubCategoryName="";
    public String AdminUserName="";
    
    
    public ProductUpdateForm() {
        
        initComponents();
        jDialog=new JDialog(this,rootPaneCheckingEnabled);
        jDialog.setBounds(this.getBounds());
        jDialog.setResizable(false);
        jDialog.add(CategoryUpdatePanelInsideTheFrame);
        jDialog.show();
    }

    public ProductUpdateForm(int TASK, String subCategoryName, String adminUserName, String productName, int productPrice, int productDiscount, int productFinalPrice, String productDescription, String productImageLink) {
        
        initComponents();
        
        this.TASK = TASK;
        this.ProductImageLink = productImageLink;
        this.SubCategoryName = subCategoryName;
        this.AdminUserName = adminUserName;
        
        ProductName.setText(productName);
        ProductPrice.setText(productPrice+"");
        ProductDiscount.setText(productDiscount+"");
        ProductFinalPrice.setText(productFinalPrice+"");
        ProductDescription.setText(productDescription);
        mSetImage(this.ProductImageLink);
        
        if(this.TASK==INSERT_NEW_PRODUCT)
        {
            ProductPrice.setText("");
            ProductDiscount.setText("");
            ProductFinalPrice.setText("");
        }
        
        jDialog=new JDialog(this,rootPaneCheckingEnabled);
        jDialog.setBounds(this.getBounds());
        jDialog.setResizable(false);
        jDialog.add(CategoryUpdatePanelInsideTheFrame);
        jDialog.show();
    }

    public void mSetImage(String imageLinkHere)
    {
        ImageIcon ic=new ImageIcon(imageLinkHere);
        Image img = ic.getImage(); 
        Image newImg = img.getScaledInstance(90, 90,Image.SCALE_SMOOTH);
        ProductImageLabel.setIcon(new ImageIcon(newImg));
    }
    
    public void InsertUpdateProduct(String categoryName, String adminName, String productName, String productImageLink, int discount, int unitPrice, String productDescription) throws SQLException, Exception
    {
        Connection c=getOracleConnection();
        CallableStatement callStmt = null;
        try 
        {
            callStmt = c.prepareCall("{call InsertUpdateProduct(?,?,?,?,?,?,?)}");
            callStmt.setString(1, categoryName);
            callStmt.setString(2, adminName);
            callStmt.setString(3, productName);
            callStmt.setString(4, productImageLink);
            callStmt.setInt(5, discount);
            callStmt.setInt(6, unitPrice);
            callStmt.setString(7, productDescription);
            
            callStmt.execute();
            
            System.out.println("Product Updated");
  
        } finally {
            callStmt.close();
            c.close();
        }
        
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryUpdatePanelInsideTheFrame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HeaderLabel = new javax.swing.JTextField();
        ProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ProductUpdateOkButton = new javax.swing.JButton();
        ProductUpdateCancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JTextField();
        ProductImageUploadButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ProductImageLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        ProductDiscount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ProductFinalPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(this.getLocation().x+225,this.getLocation().y+100);

        CategoryUpdatePanelInsideTheFrame.setBackground(new java.awt.Color(0, 140, 153));
        CategoryUpdatePanelInsideTheFrame.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CategoryUpdatePanelInsideTheFrame.setAlignmentX(0.0F);
        CategoryUpdatePanelInsideTheFrame.setAlignmentY(0.0F);
        CategoryUpdatePanelInsideTheFrame.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Name");
        jLabel1.setAutoscrolls(true);

        HeaderLabel.setEditable(false);
        HeaderLabel.setBackground(new java.awt.Color(0, 140, 153));
        HeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        HeaderLabel.setForeground(new java.awt.Color(240, 240, 240));
        HeaderLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HeaderLabel.setText("Product Category Update");
        HeaderLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ProductName.setBackground(new java.awt.Color(253, 253, 253));
        ProductName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Details");
        jLabel2.setAutoscrolls(true);

        ProductUpdateOkButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductUpdateOkButton.setText("OK");
        ProductUpdateOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductUpdateOkButtonActionPerformed(evt);
            }
        });

        ProductUpdateCancelButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductUpdateCancelButton.setText("Cancel");
        ProductUpdateCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductUpdateCancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Price");

        ProductPrice.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ProductImageUploadButton.setText("Image");
        ProductImageUploadButton.setIconTextGap(2);
        ProductImageUploadButton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        ProductImageUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductImageUploadButtonActionPerformed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(90, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(90, 90));
        jPanel1.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ProductImageLabel)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ProductImageLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);

        ProductDescription.setColumns(20);
        ProductDescription.setLineWrap(true);
        ProductDescription.setRows(5);
        ProductDescription.setWrapStyleWord(true);
        jScrollPane2.setViewportView(ProductDescription);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Discount");

        ProductDiscount.setBackground(new java.awt.Color(253, 253, 253));
        ProductDiscount.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Final Price");

        ProductFinalPrice.setBackground(new java.awt.Color(253, 253, 253));
        ProductFinalPrice.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductFinalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ProductFinalPrice.setEnabled(false);

        javax.swing.GroupLayout CategoryUpdatePanelInsideTheFrameLayout = new javax.swing.GroupLayout(CategoryUpdatePanelInsideTheFrame);
        CategoryUpdatePanelInsideTheFrame.setLayout(CategoryUpdatePanelInsideTheFrameLayout);
        CategoryUpdatePanelInsideTheFrameLayout.setHorizontalGroup(
            CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                        .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HeaderLabel)
                            .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ProductUpdateCancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(ProductUpdateOkButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                                        .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ProductDiscount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(ProductName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProductPrice, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                                .addGap(10, 10, 10)
                                                .addComponent(ProductFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ProductImageUploadButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(33, 33, 33))))
        );

        CategoryUpdatePanelInsideTheFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ProductDiscount, ProductFinalPrice});

        CategoryUpdatePanelInsideTheFrameLayout.setVerticalGroup(
            CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createSequentialGroup()
                        .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(ProductImageUploadButton))
                        .addGap(18, 18, 18)
                        .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ProductDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CategoryUpdatePanelInsideTheFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductUpdateCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductUpdateOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        CategoryUpdatePanelInsideTheFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ProductDiscount, ProductFinalPrice, ProductName, ProductPrice});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CategoryUpdatePanelInsideTheFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CategoryUpdatePanelInsideTheFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductUpdateOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductUpdateOkButtonActionPerformed

        String productName = ProductName.getText();
        int productPrice = Integer.parseInt(ProductPrice.getText());
        int productDiscount = Integer.parseInt(ProductDiscount.getText());
        String description=ProductDescription.getText();

        if(TASK==UPDATE_PRODUCT)
        {
            ProductName.setEnabled(false);
            if(!AdminUserName.isEmpty() && !SubCategoryName.isEmpty() && !ProductImageLink.isEmpty() && !ProductPrice.getText().trim().isEmpty() && productPrice>0 && !ProductDiscount.getText().trim().isEmpty() && !description.isEmpty())
            {
                try
                {
                    InsertUpdateProduct(SubCategoryName, AdminUserName, productName, ProductImageLink, productDiscount, productPrice, description);
                }
                catch (Exception ex) {
                    Logger.getLogger(CategoryUpdateForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else if(TASK==INSERT_NEW_PRODUCT) 
        {
            if(!AdminUserName.isEmpty() && !SubCategoryName.isEmpty() && !ProductImageLink.isEmpty() && !ProductPrice.getText().trim().isEmpty() && productPrice>0 && !ProductDiscount.getText().trim().isEmpty() && !description.isEmpty())
            {
                try
                {
                   
                    InsertUpdateProduct(SubCategoryName, AdminUserName, productName, ProductImageLink, productDiscount, productPrice, description);
                }
                catch (Exception ex) {
                    Logger.getLogger(CategoryUpdateForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        

    }//GEN-LAST:event_ProductUpdateOkButtonActionPerformed

    private void ProductUpdateCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductUpdateCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ProductUpdateCancelButtonActionPerformed

    private void ProductImageUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductImageUploadButtonActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogTitle("Select the Image file....");
        chooser.setMultiSelectionEnabled(false);
        chooser.setPreferredSize(new Dimension(650, 410));
        int result=chooser.showDialog(null, "Upload");

        if(result==JFileChooser.APPROVE_OPTION)
        {
            String imageLink=chooser.getSelectedFile().getPath();
            imageLink = imageLink.replace("\\", "\\\\");
            ProductImageLink=imageLink;
            mSetImage(ProductImageLink);
        }
    }//GEN-LAST:event_ProductImageUploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductUpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoryUpdatePanelInsideTheFrame;
    private javax.swing.JTextField HeaderLabel;
    private javax.swing.JTextArea ProductDescription;
    private javax.swing.JTextField ProductDiscount;
    private javax.swing.JTextField ProductFinalPrice;
    private javax.swing.JLabel ProductImageLabel;
    private javax.swing.JButton ProductImageUploadButton;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTextField ProductPrice;
    private javax.swing.JButton ProductUpdateCancelButton;
    private javax.swing.JButton ProductUpdateOkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
